### ISSUE TITLE
Module Location

### ISSUE THREAD

**Issue by joshbrinks** [ciesin-geospatial/TOPSTSCHOOL#1]
Do we intend to store the module content in this repo that serves up the website? I put stuff in content for now but we can move it around. Might need to be somewhere that the GitHub pages doesn't try to automatically compile the module documents.

**Comment by jfmartinez4** [comment]
The module is fine to live where you placed it originally. I had to change the markdown.
I replaced ```{r} with ```r

**Comment by jfmartinez4** [comment]
Moved content to separate repo
