### ISSUE TITLE
Expand glossary for all modules in a separate repo (DataTable)

### ISSUE THREAD

**Issue by jfmartinez4** [ciesin-geospatial/TOPSTSCHOOL#17]
Take the existing glossary and requirements from the water module and expand them in the main repo. Look through all of the modules, identify key words and create a glossary entry. 

Done: Google document with updated glossary
target doc: https://docs.google.com/document/d/1pyes9l03dHFjtY_jO7FZa3HhjRKExGsjg-cSa88pRMI/edit?tab=t.0

Existing glossary quarto file: https://github.com/ciesin-geospatial/TOPSTSCHOOL-water/blob/main/m0-prereq-glossary.qmd
Existing glossary page: https://ciesin-geospatial.github.io/TOPSTSCHOOL-water/m0-prereq-glossary.html

**Comment by jfmartinez4** [comment]
1.  What key words should I focus on while looking through the modules? Should I prioritize technical terms or general terms?
**Open Science (OS 101)**, **data/computer science** and **theme key words**
Keep track with Zotero: https://www.youtube.com/watch?v=77erq0hM04E

2.  How many modules should I review for the glossary is it only the water module or all other modules as well? As many as you can. For now focus on water and air quality.

3.  What format or style should I follow when writing new glossary entries? APA style for citations, emulate webster or journal articles.

4. Should I only add new terms, or should I also improve or clarify existing ones? both

5. What the official due date that I have for the task? please see task

6. To identify the definitions for each new word, did you want me to cite my sources for that definition?  yes.

7. Am I expected to do a pull request for both the new words and the citations that I have to find (if needed)? dont worry about this for now just use the google doc. 

8. What is the best form of contact if I have any other questions about the task?  this task or email.

**Comment by jfmartinez4** [comment]
- Met with Juan and received more info
- Added 5 words for glossary (water and air)
- Needs peer review for words before moving forward
- TO DO: Add Dhruvil and America's references to same Zotero folder and collection.

**Comment by jfmartinez4** [comment]
@Dalvarez40 I left comments on the google doc. Please review and let me know if you have any questions: https://docs.google.com/document/d/1pyes9l03dHFjtY_jO7FZa3HhjRKExGsjg-cSa88pRMI/edit?tab=t.0

**Comment by jfmartinez4** [comment]
@Dalvarez40 word found: Dissolve (geoprocessing)

**Comment by jfmartinez4** [comment]
@Dalvarez40 bibliography for existing references: https://github.com/ciesin-geospatial/TOPSTSCHOOL-water/blob/main/references/glossary-references.bib

**Comment by jfmartinez4** [comment]
@Dalvarez40 
TODO: 
- add all references to Zotero Glossary folder. 
- Combine the glossary words in google document. 
- Continue to look for words and add them to glossary. Places to look for words:

> - https://ciesin-geospatial.github.io/TOPSTSCHOOL-water/m101-wsim-gldas.html
> - https://ciesin-geospatial.github.io/TOPSTSCHOOL-water/m102-lance-modis-nrt-global-flood.html
> - https://topstschool.shinyapps.io/nyc-lead/
> - https://ciesin-geospatial.github.io/TOPSTSCHOOL-air-quality/m202-svi-tri-icis-places.html
> - https://ciesin-geospatial.github.io/TOPSTSCHOOL-air-quality/m203-ejscreen.html
> - https://ciesin-geospatial.github.io/TOPSTSCHOOL-air-quality/m204-grdiv1-pm25.html

**Comment by Dalvarez40** [comment]
Hello there. I will be leaving this message here to update you on my progress and I hope to discuss with you face to face. 

- I have successfully added all references from the previous glossary, along with my own references, into Zotero. (I tried to replicate each of the old glossary references as best as I can.)

-I have added 10 additional terms with references to the document, bringing the total to 15 terms that I have added to the document  to expand the glossary.

-I corrected a majority of the previous terms and fixed minor mistakes.  

- I have combined the terms that I found and the already established terms into one sorted glossary section

Issues that I had:

- This link does not work for this bibliography. Everytime that I click on this link it either gives me an error or a 404 sign. I had to look at the article myself and guess which article was the correct one as there are multiple results when I search for the title of the web page. I’m not quite sure which one it was so I had to manually create the source in zotero. 

NASA. 2019. “Earth Observing System Data and Information System (EOSDIS).” Earth Science Data Systems. https://www.earthdata.nasa.gov/eosdis.

Please look at the old citation from the glossary. 

- There were instances where I was either trying to replicate the existing glossary terms or add brand-new references to the Zotero folder, but occasionally, the references I added would disappear. I checked the deleted section to see if they were there, but they weren’t. As a result, I had to repeatedly redo many of the references. To address this issue, I created a backup folder to save them, ensuring they were preserved in case they were deleted again.

**Comment by jfmartinez4** [comment]
glossary expansion and citations created in zotero has been completed
